FROM rocker/r-ver:3.6.2
#add Ngnix for reverse proxy & authentication then apache2-utils for user management
RUN apt-get update && \
    apt-get install -y nginx apache2-utils && \
    htpasswd -bc /etc/nginx/.htpasswd test test 

RUN openssl req -batch -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/private/server.key \
        -out /etc/ssl/private/server.crt

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    file \
    libcurl4-openssl-dev \
    libedit2 \
    libssl-dev \
    lsb-release \
    psmisc \
    procps \
    wget \
    libxml2-dev \
    libpq-dev \
    libssh2-1-dev \
    ca-certificates \
    libglib2.0-0 \
	libxext6 \
	libsm6  \
	libxrender1 \
	bzip2 \
    zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/   

RUN R -e "install.packages('grDevices')"   
RUN R -e "install.packages('jsonlite')"
RUN R -e "install.packages('digest')"
RUN R -e "install.packages('htmltools')"
RUN R -e "install.packages('jquerylib')"
RUN R -e "install.packages('rlang')"
RUN R -e "install.packages('magrittr')"
RUN R -e "install.packages('SnowballC')"
RUN R -e "install.packages('tm')"
RUN R -e "install.packages('tidytext')"
RUN R -e "install.packages('stringr')"
RUN R -e "install.packages('rjson')"
RUN R -e "install.packages('e1071')"
RUN R -e "install.packages('gsheet')"
RUN R -e "install.packages('urltools')"
RUN R -e "install.packages('openssl')"
RUN R -e "install.packages('shiny')"
RUN R -e "install.packages('Rtools')"
RUN R -e "install.packages('httr')"
RUN R -e "install.packages('shinydashboard')"
RUN R -e "install.packages('lubridate')"
RUN R -e "install.packages('dplyr')"
RUN R -e "install.packages('sass')"
RUN R -e "install.packages('bslib')"
RUN R -e "install.packages('thematic')"
RUN R -e "install.packages('ggplot2')"
RUN R -e "install.packages('tidyr')"
        
ADD ./nginx.conf /etc/nginx/nginx.conf

COPY / /

EXPOSE 80 443

#CMD service nginx start && "R", "-e", "shiny::runApp('app.R', host='0.0.0.0', port=3838)"
CMD service nginx start && R -e "shiny::runApp('app.R',host='0.0.0.0', port=3838)"